# -*- coding: utf-8 -*-
"""PD-Prototype.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18PGVuHkyr9ssri1LEMCkd6-89FNcyjyM
"""

class DocumentoLegal:
    def __init__(self, tipo, contenido, nombre_cliente):
        self.tipo = tipo
        self.contenido = contenido
        self.nombre_cliente = nombre_cliente

    def clonar(self):
        # Realiza una copia profunda del objeto
        return copy.deepcopy(self)

# Crear un prototipo de documento legal
documento_prototipo = DocumentoLegal(
    tipo="Acuerdo de Confidencialidad",
    contenido="Este Acuerdo de Confidencialidad...",
    nombre_cliente="Cliente A"
)

# Clonar el prototipo para un nuevo cliente
documento_clonado = documento_prototipo.clonar()
documento_clonado.nombre_cliente = "Cliente B"

# Mostrar los detalles de los documentos
print(f"Documento Original: Tipo: {documento_prototipo.tipo}, Cliente: {documento_prototipo.nombre_cliente}")
print(f"Documento Clonado: Tipo: {documento_clonado.tipo}, Cliente: {documento_clonado.nombre_cliente}")